//vars for task Cutadapt from catalog SmallRNAseq, version 0.1
// FASTQC_OUTDIR=QC + "/fastqc"
// FASTQC_THREADS=4

CUTADAPT_OUTDIR=RESULTS + "/processed_reads"
ADAPTER_SEQUENCE="-a AGATCGGAAGAGCACACGTCT" // other adapters: 
/* "-a CGACAGGTTCAGAGTTCTACAGTCCGACGATC -a AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT 
 -a AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA 
 -a CTGTCTCTTATACACATCTCCGAGCCCACGAGAC 
 -a AGATCGGAAGAGCGGTTCAGCAGGAATGCCGAG 
 -a TACAGTCCGACGATC 
 -a ATCTCGTATGCCGTCTTCTGCTTG 
 -a TGGAATTCTCGGGTGCCAAGG 
 -a TGGAATTCTCGGGTGCCAAGGAACTCCA 
 -a TCGTATGCCGTCTTCTGCTTGT 
 -a CAAGCAGAAGACGGCATACGA 
 -a CAAGCAGAAGACGGCATACGAGATCGTGATGTGACTGGAGTTC 
 -a CAAGCAGAAGACGGCATACGAGATTACAAGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA 
 -a AATGATACGGCGACCACCGACAGGTTCAGAGTTCTACAGTCCGA -a CAAGCAGAAGACGGCATACGAGATATTGGCGTGACTGGAGTTC  -a GGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGCCGTCT -a GGAAGAGCACACGTCTGAACTCCAGTCACACTTGAATCTCGTATGCCGTCT -a GGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCT"*/
MINIMUM_OVERLAP=5
MINIMUM_LENGTH_KEEP=MIN_LENGTH
MAXIMUM_LENGTH_KEEP=MAX_LENGTH
