//vars for task Cutadapt from catalog SmallRNAseq, version 0.1
// FASTQC_OUTDIR=QC + "/fastqc"
// FASTQC_THREADS=4

CUTADAPT_OUTDIR=RESULTS + "/processed_reads"
ADAPTER_SEQUENCE="-a TGGAATTCTCGGGTGCCAAGG -a TGGAATTCTCGGGTGCCAAGGAACTCCA -a TCGTATGCCGTCTTCTGCTTGT -a CAAGCAGAAGACGGCATACGA -a CAAGCAGAAGACGGCATACGAGATCGTGATGTGACTGGAGTTC -a CAAGCAGAAGACGGCATACGAGATTACAAGGTGACTGGAGTTCCTTGGCACCCGAGAATTCCA -a AATGATACGGCGACCACCGACAGGTTCAGAGTTCTACAGTCCGA -a CAAGCAGAAGACGGCATACGAGATATTGGCGTGACTGGAGTTC -a AGATCGGAAGAGCACACGTCT -a GGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGCCGTCT -a GGAAGAGCACACGTCTGAACTCCAGTCACACTTGAATCTCGTATGCCGTCT -a GGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCT"
MINIMUM_OVERLAP=8
MINIMUM_LENGTH_KEEP=21
MAXIMUM_LENGTH_KEEP=51
