//vars for task MirDeep2 from catalog SmallRNAseq, version 0.1

MIR_OUTDIR=RESULTS + "/mirDeep2"
GENOME_SEQ=ESSENTIAL_GENOME_REF
MATURE_MIRNA=ESSENTIAL_MATURE_MIRNA
HAIRPIN_MIRNA=ESSENTIAL_HAIRPIN_MIRNA
