REPENR_OUT_DIR=RESULTS + "/repEnrich"
REPENRICH_THREADS=16			// threads to use
REPENRICH_ESSENTIAL_THREADS=ESSENTIAL_THREADS            // threads to use
REPENRICH_REF=ESSENTIAL_BOWTIE_REF // prefix of the bowtie reference genome
REPENRICH_MM=ESSENTIAL_MISMATCHES             // number of mismatches allowed
REPENRICH_MULTIMAP=1       // discard reads mapping to more than MULTIMAP positions
REPENRICH_MULTIREPORT=1       // if a read has more than <int> reportable alignments, one is reported (as mapped) at random.
REPENRICH_BEST="--tryhard --best --strata --chunkmbs 256"	// bowtie best mode
REPENRICH_QUALS="--phred33-quals"	// phred33-quals. Use --phred64-quals for old sequencing runs
REPEAT_REF=ESSENTIAL_REPEAT_REF
REPEAT_MASKER=ESSENTIAL_REPEAT_MASKER