//vars for task FilterRNAClasses from catalog SmallRNAseq, version 0.1

FILTER_CLASSES_TOOL_PATH=ESSENTIAL_PROJECT + "/NGSpipe2go/tools/smallRNA/filterSmallRNAclasses.py"
FILTER_CLASSES_OUTDIR=RESULTS + "/small_RNA_classes"
FILTER_CLASSES_21U_REF=ESSENTIAL_21U_REF
FILTER_CLASSES_22G_REF=ESSENTIAL_22G_REF
FILTER_CLASSES_26G_REF=ESSENTIAL_26G_REF

