FILBOWTIE2UNIQUE_MAPPED=MAPPED
FILBOWTIE2UNIQUE_SAMTOOLS_THREADS=ESSENTIAL_THREADS
FILBOWTIE2UNIQUE_GENOME=ESSENTIAL_BOWTIE_GENOME
FILBOWTIE2UNIQUE_SAMTOOLS_THREADS=" -@ " + Integer.toString(ESSENTIAL_THREADS) // threads to use
