//vars for task qualimap 
QUALIMAP_OUTDIR=QC + "/qualimap"
QUALIMAP_STRANDED=ESSENTIAL_STRANDED // options are no/yes/reverse 
QUALIMAP_GENESGTF="-gtf " + ESSENTIAL_GENESGTF
QUALIMAP_EXTRA="--java-mem-size=4G"
QUALIMAP_PAIRED=ESSENTIAL_PAIRED
