//vars for task rMatas
RMATS_OUTDIR=RESULTS + "/rMATS"
RMATS_POSTFIX=PREMATS_POSTFIX
RMATS_SEP="vs";
RMATS_PAIRED=ESSENTIAL_PAIRED
RMATS_GTF=ESSENTIAL_GENESGTF
RMATS_ANCHOR=8
RMATS_LEN=ESSENTIAL_READLENGTH 
RMATS_TYPE="U" // type of the analys P = paired U=unpaired
RMATS_CUTOFF=0.0001 //cutoff for the null hyptohtesis test

