//vars for task rMatas
RMATS_OUTDIR=RESULTS + "/rMATS"
RMATS_POSTFIX=PREMATS_POSTFIX
RMATS_SEP=".vs.";
RMATS_PAIRED=ESSENTIAL_PAIRED
RMATS_STRANDED=ESSENTIAL_STRANDED
RMATS_GTF=" --gtf " + ESSENTIAL_GENESGTF
RMATS_LENGTH=" --readLength " + ESSENTIAL_READLENGTH
RMATS_THREADS=" --nthread " + Integer.toString(ESSENTIAL_THREADS) 
RMATS_EXTRA=" --cstat 0.0001"

