GATK_THREADS=Integer.toString(ESSENTIAL_THREADS)
GATK_BWA_REF=ESSENTIAL_BWA_REF
GATK_KNOWN_VARIANTS=ESSENTIAL_KNOWN_VARIANTS
GATK_REFCONF="--emitRefConfidence GVCF"
GATK_INDEXTYPE="--variant_index_type LINEAR"
GATK_INDEXPARM="-variant_index_parameter 128000"
GATK_EXTRA=""

