//vars for task miRDeep2 from catalog smallRNAseq_BCF, version 0.1

MIR_OUTDIR=RESULTS + "/miRDeep2"
GENOME_SEQ=ESSENTIAL_GENOME_REF
MATURE_MIRNA=ESSENTIAL_MATURE_MIRNA
HAIRPIN_MIRNA=ESSENTIAL_HAIRPIN_MIRNA
SPECIES=ESSENTIAL_SPECIES
